In [1]:
import numpy as np

In [3]:
a1 = np.random.rand(4)
a1

array([0.34561153, 0.14355704, 0.40822376, 0.85168606])

In [4]:
a2 = np.random.rand(4,1)
a2

array([[0.57797691],
       [0.77618954],
       [0.92418074],
       [0.65028992]])

In [5]:
a3 = np.array([[1,2,3,4]])
a3

array([[1, 2, 3, 4]])

In [6]:
a4 = np.arange(1,4,1)
a4

array([1, 2, 3])

In [7]:
a5 = np.linspace(1,4,4)
a5

array([1., 2., 3., 4.])

In [9]:
a4.ndim

1

In [10]:
a1.shape == a5.shape

True

In [11]:
a3.shape == a4.shape

False

In [12]:
a1.shape == a2.shape

False

In [13]:
old = np.array([[1,1,1], [1,1,1]])
new = old
new[0,:2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [16]:
import re
s = 'ACBCAC'
re.findall('^AC', s)



['AC']

In [19]:
s1 = 'ACAABAACAAAB'
result = re.findall('A{1,2}',s1)
L = len(result)
print(L)

5


In [21]:
text = '''Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'''

In [22]:
type(text)

str

In [23]:
pattern = '[(]\d{3}[)]\s\d{3}[-]\d{4}'
re.findall(pattern, text)

['(734) 647-6333',
 '(734) 647-8044',
 '(734) 763-2285',
 '(734) 647-3576',
 '(734) 763-1251',
 '(734) 764-9376']

In [24]:
text1 = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'

In [41]:
pattern1 = '(\/\/)([\w.]*[\s]*)'
for item in re.finditer(pattern1, text1):
    print(item.group(2))

google.com 
www.baidu.com 


In [59]:
pattern2 = '(?<=[https]:\/\/)([\w.]*[\s]*)'
for item2 in re.finditer(pattern2, text1):
    print(item2.group(1))

google.com 
www.baidu.com 


In [62]:
text10=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''


pattern10 = '\(.\)'
print(len(re.findall(pattern10,text10)))

4
